### PR TITLE
Make Mailspring ID optional, allow plugins to indicate dependency on synced metadata

### PR DESCRIPTION
**Pull request by bengotow**
Hey folks - this one has been a long time coming, but here we go!

This PR makes the Mailspring ID optional. When you launch the app for the first time, you can now bypass the Mailspring ID setup screen by choosing "Not Now" on the create an account page (it's at the bottom beneath sign in). The app reminds you that some features will be disabled, and then you're set!

When you opt out of the Mailspring ID, the value of `IdentityStore.identity()` is just `null`, rather than a placeholder identity or something like that. This required a few more code changes but it felt like the right approach.

On the mailsync side (also now GPLv3!), the tasks that sync message metadata to the cloud become no-ops and the metadata sync worker is disabled, but that's about all that had to change there. There is still one place where we use `https://id.getmailspring.com` to resolve CalDAV DNS but that API endpoint has been changed to not require auth. I think in the future this could be removed, but CalDAV uses some bizarre DNS records to indicate where the caldav root for an email domain is, and I wasn't able to get the DNS queries to work from C++ on Windows so I implemented them on the server.

There are several plugins like thread-sharing, translation and read-receipts that don't work at all without Mailspring's web services, and I updated the package manager so that these plugins can specify `isIdentityRequired: true` in their `package.json` files and be automatically disabled when a Mailspring ID isn't present.  The snooze plugin /mostly/ works without a Mailspring ID (since the cloud metadata sync is more optional there), but without the cloud saving your snooze dates any event that causes a full mail resync will wipe the local metadata table and reset snoozes, which could be pretty annoying. I disabled that one too, and maybe if there's a lot of interest we could evaluate how to make the local cache more persistent.

@notpushkin I'd love to get your thoughts about this since you've been leading the charge on Mailspring-Libre and have a better idea of what this slice of the Mailspring community is looking for! This PR leaves a lot of the links in the app (to documentation, setup guides etc) untouched, but I went through the mailspring-libre <> mailspring diff and tried to pull in the work of the community. Let me know if there's anything I missed - I'm sure there's more we can work on once this merges!

Also as a sidenote, while fixing this stuff I was relaunching Mailspring over and over and I was able to reproduce a C++ "dangling process at 100% CPU" issue that I think was reported elsewhere! Excited to get that fixed too.

### CODE REVIEW

**Review by CodeMouse92 — COMMENTED** [review]
While it looks good, I'm unable to run the code with `npm start`. Ubuntu 20.04, and I can run `master` just fine. ~~Logs below.~~

**EDIT:** No, I take that back, after updating `master`, it will no longer run.

**EDIT 2:** `npm install` would help. Sheeeeeeeesh, my brain. 🧠

**Review by CodeMouse92 — APPROVED** [review]
Excellent! Love the workflow.

**Comment by notpushkin** [comment]
I've looked through the commits and things look pretty good to me! I might have a few ideas / suggestions in mind which are related but still out of scope of this PR. Going to give it a try over the next week and let you know :-)

**Comment by WardBenjamin** [comment]
This currently breaks sign-in with Google. I'm not sure about other providers. 

image

```
....\Mailspring\app\src\error-logger.js:101 Error: Your Mailspring ID is missing required fields - you may need to reset Mailspring. http://support.getmailspring.com/hc/en-us/articles/115002012491
    at ChildProcess.<anonymous> (mailsync-process.ts:231)
    at ChildProcess.emit (events.js:210)
    at ChildProcess.EventEmitter.emit (domain.js:476)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283) {pluginIds: Array(0)}
```

Also - thank you very much, this is a fantastic feature!

**Comment by Phylu** [comment]
@bengotow Is there anything, we can do to support you with this? Testing of certain cases of so?

**Comment by bengotow** [comment]
Hey @Phylu! Going to see if I can address the remaining feedback and get this merged today actually 🙌  I've been using it for a week or two and I think we're almost there. I think that the scenario @WardBenjamin ran in to might be caused by misalignment between the mailspring-sync binary and the mailspring UI which shouldn't be a problem once this PR merges!

**Comment by CodeMouse92** [comment]
:tada:

**Comment by Phylu** [comment]
@bengotow I just tried out these changes on a fresh master branch. There were some issues:

1. I had my previous Mailspring ID configured and then started Mailspring with these changes. When I tried to connect a new GMail Account, I got the same error as @WardBenjamin. It seems to me that there is a problem with the stored Mailspring ID (in the config directory) that is incompatible to the changes, as removing the directory `/home/phylu/.config/Mailspring-dev` resolves the issue.
2. On the Mailspring ID Setup page, there is some text in English even though my German localization. However, I cannot find the text in question in the repo. It seems that there is an external page (from getmailspring.com) embedded here. If you want a German translation let me know, how I can provide it best.
3. When I skip the setup of a Mailspring ID and then try to register a GMail account, Mailspring does not pick up the OAuth Response. It gets stuck at screen [1]. The last log message displayed is [2]. When I log in to my Mailspring ID, the GMail account can be added without any troubles.

[1]
Bildschirmfoto von 2021-04-05 11-51-32

[2]
```
"Using Mailcore Template: {
  "servers": {
    "imap": [
      {
        "port": 993,
        "hostname": "imap.gmail.com",
        "ssl": true
      }
    ],
    "smtp": [
      {
        "port": 587,
        "hostname": "smtp.gmail.com",
        "starttls": true
      },
      {
        "port": 465,
        "hostname": "smtp.gmail.com",
        "ssl": true
      },
      {
        "port": 25,
        "hostname": "smtp.gmail.com",
        "starttls": true
      }
    ]
  },
  "mx-match": [
    "aspmx2\\.googlemail\\.com",
    "aspmx\\.l\\.google\\.com",
    "aspmx3\\.googlemail\\.com",
    "alt1\\.aspmx\\.l\\.google\\.com",
    "alt2\\.aspmx\\.l\\.google\\.com",
    "alt1\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt2\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt3\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt4\\.gmail-smtp-in\\.l\\.google\\.com",
    "gmail-smtp-in\\.l\\.google\\.com"
  ],
  "domain-match": [
    "googlemail\\.com",
    "gmail\\.com"
  ],
  "mailboxes": {
    "sentmail": "[Gmail]/Sent Mail",
    "allmail": "[Gmail]/All Mail",
    "starred": "[Gmail]/Starred",
    "trash": "[Gmail]/Trash",
    "drafts": "[Gmail]/Drafts",
    "spam": "[Gmail]/Spam",
    "important": "[Gmail]/Important"
  }
}", source: /home/phylu/git/Mailspring/app/internal_packages/onboarding/lib/onboarding-helpers.ts (114)
```

**Comment by bengotow** [comment]
Hmm thanks for testing this @Phylu, looking in to those issues now! Will see if I can reproduce by downgrading and re-upgrading to master.

**Comment by bengotow** [comment]
Hey folks! I played around with the downgrade / upgrade process and I wasn't able to reproduce the problem you guys were both seeing, which feels a bit odd. I'm going to try tomorrow on a fresh computer and in my Windows VM where I can download 1.8.9 and then 1.9.0 and see if it happens.

In the meantime, could you try downloading the compiled version and see if you still run into trouble?
https://s3.amazonaws.com/mailspring-builds/client/7e3448ad/osx/Mailspring.zip
https://s3.amazonaws.com/[secure]/client/7e3448ad/linux/mailspring-1.9.0-amd64.deb

(Windows build is still failing, need to fix this tomorrow: https://ci.appveyor.com/project/Foundry376/merani/builds/38645896)

In addition to making the Mailspring ID optional, this release also upgrades us to Electron 8, so it's possible that there's been some other regression and Mailspring isn't retrieving your passwords from your system keychain properly, but I hope not. It's also possible that when you ran after an npm-install, Electron.app had been updated to a new version and the system opened a "unlock your keychain" prompt? I know getting one of those and clicking "No" can cause this sort of thing.

**Comment by Phylu** [comment]
I did the upgrade of the production builds that I am using on Mac on Ubuntu and there everything worked fine. I did not try a setup without the Mailspring ID yet, but so far it seems fine now. Might have been some inconsistencies in the dev user folder.

I also did not get an "unlock your keychain" prompt. So as far as I am concerned: Great work! Seems good to be released like this :)

**Comment by Phylu** [comment]
I just tested it on ubuntu with out the Mailspring ID. The account setup works here as well.

Strangely it is still not working with the dev version started by npm. Somehow it seems that the OAuth response is not coming through to Mailspring in this case. But the build seems fine!

**Comment by WardBenjamin** [comment]
I'm happy to try this out as soon as the Windows build is successful! 

The dev version started by npm still isn't working for me, same problem as above.

**Comment by bengotow** [comment]
Hey folks! Thank you for all the feedback - it's good to know something is still weird about the dev setup, but I'm glad the release builds are working. I /finally/ got AppVeyor to build (apparently npm started automatically running `npm audit` at the end of scripts like `npm install`, and if it returns a single warning they exit with error code 1...) @WardBenjamin could you give this build a spin? https://mailspring-builds.s3.amazonaws.com/client/2b880693/win-ia32/MailspringSetup.exe

Cheers! Thanks everyone - will keep investigating that dev issue.

**Comment by WardBenjamin** [comment]
It looks like everything is working! I was able to skip the ID requirement, link my Gmail account with the OAuth flow, and proceed to writing this reply as an email.

**Pull request merged**
