### PR TITLE
add frame and remove toolbar from calendar preview

### LINKED ISSUE #1541: Calendar preview has no close button
I am using Mailspring 1.6.2 and tried the Calendar Preview via Developer => Calendar Preview. It opens the calendar with all my Google Calendars, but there is no close button. So I have to close the window using the icon on the taskbar, which is not very user friendly. Please add some chrome to the Calendar Preview window with a fullscreen, minimize and at least a close button. 

To fix this, you only have to change the window options in `src/browser/window-manager.ts` to `frame: true`. I would also hide the menu, but am not sure where to do that...

### PR DESCRIPTION
**Pull request by mslourens**
fixes #1541 - just enable the frame and disable the toolbar, that's all.

### CODE REVIEW

**Comment by Hype-Rat** [comment]
Hi @mslourens! I fixed your issue. The calendar have now close button :)

**Comment by mslourens** [comment]
Thanx @Hype-Rat, but as you can see, I already fixed the issue myself...

**Comment by bengotow** [comment]
Thanks @mslourens, sorry for the long delay getting this reviewed and landed. Looks good to me! There will be another big iteration of the calendar stuff merging soon so we should definitely get this in first.

**Comment by pablorq** [comment]
This is still happening. I think that the merge is not on the version 1.6.3-134a0e55. :(

**Pull request merged**
