### PR TITLE
Fix sync issue windows 11

### PR DESCRIPTION
**Pull request by ronymesquita**
Hello.

I have had a few problems with Mailspring on Windows 11, like discussed in this link [https://community.getmailspring.com/t/gmail-account-keeps-on-disconnecting-every-time-pc-restarts/1720](https://community.getmailspring.com/t/gmail-account-keeps-on-disconnecting-every-time-pc-restarts/1720). After restart, Mailspring stopped syncing Gmail.
In this pull request i updated better-sqlite3 and changed postinstall.js to avoid these problems.

I tested on Ubuntu 22.04 and Windows 11. Both worked, including Grunt build.

Windows 11:
Python 3.10.4 (Microsoft Store)
Node.js 16.14.2
NPM 8.7.0

Ubuntu 22.04:
Python 3.9.7
Node 16.13.1
NPM 8.7.0

### CODE REVIEW

**Comment by bengotow** [comment]
Hey @ronymesquita thanks for committing this! Do you know if the fix was updating to better-sqlite 7.5.1, or moving the Windows build to 64-bit? I think it's probably safe to do both, but technically this new version won't launch on older 32-bit windows machines anymore?

**Comment by ronymesquita** [comment]
Currently, 32 -bit Windows has low market share. Perhaps it is not a real problem to remove compatibility.

https://www.pcbenchmarks.net/os-marketshare.html
https://store.steampowered.com/hwsurvey (section OS version)

**Comment by ronymesquita** [comment]
Hello.
Please @bengotow, can you review this pull request?

**Comment by bengotow** [comment]
Hey @ronymesquita, sorry for the delay - I'm not 100% sure which change here fixes the issue (the 7.5.0 => 7.5.1 update to better-sqlite3 changelog isn't super exciting), but I'm game to drop win32 support and move everything to 64-bit on Windows. I think that we may need to swap out a few other ia32 pieces so the entire app is 64-bit. Will take a look real quick!

**Review by bengotow — APPROVED** [review]

**Pull request merged**
