### PR TITLE
Fixes #2039: wrong time in event header due to timezone mismatch

### LINKED ISSUE #2024: Bug: Incorrect time when receiving Zoom meetings
It appears that when I receive a Zoom meeting request from someone in a different timezone, the time for that meeting is incorrect when I read the invite in Mailspring, but when I review my calendar (Google), the meeting is scheduled correctly.  To be honest, I've not noticed this happen with other meeting providers, but I will keep an eye out for them.  

In the attached image, the scheduled time for the meeting is 9am PDT but as you can see, it appears as 11am PDT in Mailspring. When I review my Google calendar, it appears as 9am PDT. The email originated from someone located in the Central time zone, two hours ahead of my (Pacific) time zone.

Screenshot from 2020-05-26 11-47-57

**Setup: (please complete the following information):**
 - OS: Ubuntu 18 Desktop
 - Mailspring Version: ex: 1.7.8 (13635bcf)

### LINKED ISSUE #2039: Bug: Timezone handling for event invites is incorrect
**Describe the bug**
When you receive an event invite, the time displayed is in the _senders_ local time, but the timezone displayed is the _received_ timezone.

For example, if I, as the sender am in Bulgaria (EEST (UTC+3)), and I send an invite for an event at 4pm EEST to a recipient in the UK (BST (UTC+1)), the recipient should see the invite time as 2pm BST. However instead it displays 4pm BST (the senders time, but with BST as the timezone).

Have logged into GMail and confirmed that, in GMail, the correct time is displayed (2pm BST):

Incorrect time shown in Mailspring

Correct time shown on GMail

**To Reproduce**
1. Send an invite (likely _not_ by using Mailspring) from one timezone (e.g. EST)
2. Receive the invite via Mailspring with your setup to use a different timezone from the original invite (e.g. PST)
3. See the time as being the invite time from the sender, but suffixed with your local timezone.

**Expected behavior**
Either a) The time should be shown using the senders time _and_ timezone (not ideal), or the time should be showng and converted to your timezone (preferable).

**Screenshots**
See above

**Setup: (please complete the following information):**
 - OS: Fedora
 - OS Fedora release 28 (Twenty Eight)
 - Mailspring Version: 1.7.6

**Additional context** 
Have only tested _receiving_ invites into a GSuite/GMail account -  haven't tested sending them, or seeing if the same issue exists when receiving invites through other mail providers, although I cannot see why it wouldn't.

### PR DESCRIPTION
**Pull request by tecoholic**
This probably also close #2024 #1546 and #1555 

## Background

The time displayed on the event-header component is wrong. In my case, it displayed the same time with the wrong timezone.

wrong_time

8AM-9AM New York timezone is actually 5.30PM-6.30PM Indian Standard Time (IST)

### Bug location

Based on the link from #1546, the bug was located in the [event-header.tsx](https://github.com/Foundry376/Mailspring/blob/33aba8f31fbbbcda924d335804801fcbb4e13f0d/app/internal_packages/events/lib/event-header.tsx#L108) file.

### Investigating the code

Added the following lines to see what is happening in the time conversion.

```js
console.log("Event enddate", icsEvent.endDate);
console.log("Event enddate zone", icsEvent.endDate.zone.toString());
console.log("Event enddate utc offset", icsEvent.endDate.utcOffset());
console.log("Event enddate JSDate", icsEvent.endDate.toJSDate());
```

And got the following output:
log

Turns out the timezone information that is available in the `timezone` parameter of the ICAL.js library's Event's `endDate` is not stored in its `zone` attribute and instead, it shows the zone as `floating`. To check if iCal.js is parsing it wrong, I looked at the email data, here is the event

```
--000000000000dbd9b005aa540667
Content-Type: text/calendar; charset="UTF-8"; method=REQUEST
Content-Transfer-Encoding: 7bit

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT

DTSTART;TZID=America/New_York:20200714T080000
DTEND;TZID=America/New_York:20200714T090000

DTSTAMP:20200713T150552Z
ORGANIZER;CN=<redacted>
UID:<redacted>
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE
 ;CN=<redacted>;X-NUM-GUESTS=0:<redacted>
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=<redacted>;X-NUM-GUESTS=0:<redacted>
X-MICROSOFT-CDO-OWNERAPPTID:-567554629
RECURRENCE-ID;TZID=America/New_York:20200716T083000
CREATED:20190604T120754Z
DESCRIPTION:-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~::~:~::-\nPlease do not edit this section of the descriptio
 n.\n\nView your event at <redacted>-::~:~::~:~:~:
 ~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
LAST-MODIFIED:20200713T150551Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:<redacted>
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

--000000000000dbd9b005aa540667--
```

It can be seen that, both DTSTART and DTEND values have clear timezone information in them and id not marked as a floating timezone. At this point, it seems like a bug in the iCal.js library's parsing.

## Workaround

Until the upstream library (ical.js) fixes the parsing and gets the `timezone` information translated into the `zone` attribute, Mailspring will have to perform the conversion using **moment.js**

## Solution

This PR implements the above-mentioned workaround by creating a datetime object using the `timezone` attribute from the ical's `startDate` and `endDate` values.

Here is the right output of the event after the fix

image

P.S: A couple of unanticipated changes got added like updated versions in package.json and package lock. A small shift on the `RetinaImg` block due to linting. I noticed it only when writing the PR. Sorry about that.

### CODE REVIEW

**Comment by tecoholic** [comment]
Reminder ping

**Comment by bengotow** [comment]
Hey @tecoholic thanks for filing this, and for the detailed investigation! I think you're right that the problem is really on the ics parsing side - the library really shouldn't expect you to apply the timezone on your own. I took a look through their issues and it seems like there are quite a few edge cases they might be handling incorrectly! https://github.com/mozilla-comm/ical.js/issues?q=is%3Aopen+is%3Aissue+timezone

This all looks great though - until we can fix it on the ical.js side I think this is the ideal solution. Will get this shipped!

**Comment by D4V3M0NK** [comment]
Can I ask - I use the snap version of Mailspring on Ubuntu18. If you've now pushed this change to master, I should just be able to close down Mailspring and then open it up again, it should automatically update, correct? At the moment it looks like I'm running `1.7.8-13635bcf` ... should I be looking for the commit number **(8b57cb4)** to ensure that my version got updated?

**Comment by CodeMouse92** [comment]
@D4V3M0NK There was a delay in the next version being pushed out --- blame 2020 for that. This will appear in the next release, which should be later this week!

---

Meanwhile, @tecoholic, I just wanted to let you know that we've launched the [Mailspring Community](https://community.getmailspring.com). It will be home to all future bug reports, feature suggestions, and plenty of development discussion. We'd love for you to join! When you do, you can request to be a member of the Contributors group here: https://community.getmailspring.com/g/contributors

Looking forward to seeing you on there!

**Comment by dquintani** [comment]
I'm still getting the issue, currently using the latest version (1.10.2-69a03d6d). 

This is supposed to say April 4th, 10:30am
image

**Comment by Phylu** [comment]
@dquintani Thanks for your e-mail! Can you please answer the following questions:

- Which Operating System are you using? 
- Which system do you use to create the invite?
- What is the timezone on the system used to create the invite?
- What is the timezone on the system where you receive the invite with Mailspring?

This may help to figure out where exactly the problem is.

**Pull request merged**
