### PR TITLE
Add support for Yahoo! Brasil

### LINKED ISSUE #2273: Add Yahoo! Brasil Support
## Objective
It appears that `yahoo.com.br` is not supported. It defaults to using the domains for Yahoo! (presumably), rather than the domains for Yahoo! Brasil.

## Testing Notes

I've asked the original poster to test the fix.

## Tips

I think we can use the difference between `yahoo.com` and `yahoo.co.jp` accounts as a model to fix this.

## References

https://community.getmailspring.com/t/problem-to-add-a-yahoo-com-br-account/356

### PR DESCRIPTION
**Pull request by CodeMouse92**
Resolves #2273 (at least, hopefully)

### CODE REVIEW

**Comment by CodeMouse92** [comment]
Resolves #2273

**Comment by CodeMouse92** [comment]
Waiting on @josiasmat (original bug reporter) to test.

**Comment by bengotow** [comment]
Rebasing this on master to remove the four account limit related changes now that those have merged!

**Comment by bengotow** [comment]
This looks good but I'm wondering whether it'll be `smtp.mail.yahoo.co.br` or `smtp.mail.yahoo.com.br` - it looks like it may be the latter but would be great to have @josiasmat plug the options in to the IMAP/SMTP setup screen in Mailspring and see which values work!

```
bengotow@Bens-2019-MBP ~ % ping smtp.mail.yahoo.com.br
PING smtp.mail.global.gm0.yahoodns.net (74.6.141.43): 56 data bytes
64 bytes from 74.6.141.43: icmp_seq=0 ttl=51 time=38.559 ms

bengotow@Bens-2019-MBP ~ % ping smtp.mail.yahoo.co.br 
ping: cannot resolve smtp.mail.yahoo.co.br: Unknown host
```

**Comment by CodeMouse92** [comment]
@bengotow He actually reported an error message with the JSON file I changed, so I still have to go back and fix that today. (Was going to last week, but then my week turned into a slime monster.)

**Comment by CodeMouse92** [comment]
@bengotow I fixed a fatal typo in the JSON. I'm also fairly sure it's `.com.br`, *not* `.co.br`, [which doesn't even appear to be a valid TLD/SLD](https://en.wikipedia.org/wiki/.br#Second-level_domains).

**Comment by CodeMouse92** [comment]
Based on https://community.getmailspring.com/t/problem-to-add-a-yahoo-com-br-account/356/10 (and following), this is not the fix.

Yarg.

**Pull request closed without merging**
