### PR TITLE
0.3.27 - language support/i translate

### PR DESCRIPTION
**Pull request by AbiertaMente**
let me translate this app for es_ES

### CODE REVIEW

**Comment by bengotow** [comment]
Hey! Thanks for getting this started! It looks like this pull request may be comparing two existing branches of the project when you may mean to fork the project, create a branch of your own, and send a pull request for that one?

**Comment by AbiertaMente** [comment]
Hey, I'm willing to help with the translate, but I'm not so pro with javascript. As much as I can do is get some strings and translate them, usually I use gettext for that, thing doesn't works in javascript as far as I know.

Can you give me a clue about how to get your strings and create a .po (or equivalent) file to give internationalitation? if you feel too tired for get this just ignore me

--
We are not what we eat, we are what we decide
twitter.com/AbiertaMente
--

**Comment by bengotow** [comment]
Hey! If that's the case, could you sign up on the Google form mentioned here? #226 We'll get started on the extraction of strings soon.

**Comment by AbiertaMente** [comment]
done, nice work Ben

**Pull request closed without merging**
