### PR TITLE
Colorize Accounts

### PR DESCRIPTION
**Pull request by Phylu**
This PR implements the possibility to colorize accounts. The account colors are used to have an easier differentiation between accounts when multiple accounts are used. This PR:
* Resolves https://github.com/Foundry376/Mailspring/issues/2184
* Resolves https://github.com/Foundry376/Mailspring/issues/526
* Resolves https://github.com/Foundry376/Mailspring/issues/1738

What is still missing is a "live refresh" when the account color is changed in the preferences. So far the UI elements are not updated automatically.
* The colors in the RootSidebar only refresh after restarting Mailspring
* The colors in the mail ThreadList only refresh after a reload of the ThreadList (e.g. switching the reading pane from on to off or vice versa)

I would highly appreciate any hints on how to ensure that the UI is refreshed properly to finish this feature.

### CODE REVIEW

**Comment by bengotow** [comment]
Wow this looks really cool - nice work! 🙌  I appreciate you using Typescript types for the style props too :-) 

I think that the best way to trigger a re-render of the ThreadList and account sidebar when changing the accounts is to make sure that both of those components are "listening" to the AccountStore (subscribed via a `.listen()` call in componentDidMount or via a fancy RxJS Observable), and then using one of the AccountStore actions like `Actions.updateAccount` to save the changes. 

I /think/ that should already be the case though—I'm sorta surprised it's not already updating! Let me pull down your branch real quick and I'll point you in the right direction!

**Comment by bengotow** [comment]
Hey @Phylu - ok, I looked into why the UI wasn't updating when the accounts were modified. It looks like the accounts are being saved, and the AccountStore is "triggering" (emitting it's change event). The top level components of the sidebar and thread list update, but parts of the component tree have "shouldComponentUpdate" methods that evaluate the props they're getting and choose not to re-render because the data they're being provided hasn't changed.

Implementing `shouldComponentUpdate` always makes these things a bit more of a pain, but it helps save a lot of re-rendering. In the ThreadListParticipants case we don't really want to make the thread list re-render whenever accounts change, because things like sync status change often and wouldn't matter. It'd be a bit of a pain to collect the account colors and pass them down in to the participants component as a prop because there are a bunch of layers of components. 

React Context might be a good solution, because it allows you to expose some ambient data for an entire tree of components and then reference it many components down without having to pass it as a prop each step of the way. In this case though, using a Context would require us to add a new component wrapping the whole ThreadList and providing colors as a context up in ThreadList.tsx. It'd work, but it spreads the code out a bit.

It might be easier (and a bit more self-contained) to make the color bar work the way MailImportantIcon does, where the bar is a tiny React component that listens to the AccountStore on it's own and updates it's color. Here's what that might look like:

```

class AccountColorBar extends React.Component<{ accountId: string }, { color: string | null }> {
  static displayName = 'AccountColorBar';

  unsubscribe?: () => void;

  constructor(props) {
    super(props);
    this.state = { color: this.getColor(props) };
  }

  getColor = (props = this.props) => {
    const account = AccountStore.accountForId(props.accountId);
    return (account && account.accountColor) || null;
  };

  componentDidMount() {
    this.unsubscribe = AccountStore.listen(() => {
      const nextColor = this.getColor();
      if (this.state.color !== nextColor) this.setState({ color: nextColor });
    });
  }

 componentWillUnmount() {
    this.unsubscribe && this.unsubscribe();
  }

  render() {
    return this.state.color ? (
      <span
        style={{
          height: '50%',
          paddingLeft: '4px',
          borderLeftWidth: '4px',
          borderLeftColor: this.state.color,
          borderLeftStyle: 'solid',
        }}
      />
    ) : (
      <span />
    );
  }
}

```

Then in ThreadListParticipants, we could say something like this:

```
      <div className="participants" dir="auto">
        <AccountColorBar accountId={this.props.thread.accountId} />
        {this.renderSpans(items)}
      </div>
```

For the sidebar, I think the fix is to make the account color part of the OutlineViewProps at `outline-view.tsx:32` (maybe we could call it `titleAccountColor` to go along with `title`?) and set it to the account.accountColor at `sidebar-section.ts:243`. Then you can use it in place of the AccountStore color lookup in the render method, and it'll be part of the data that determines whether things re-render!

Also looked through the rest of this and it looks great! Love that you got it in the from picker dropdown too. What do you think about calling the `Account` property `tintColor` or just `color`?  I have a feeling we'll keep finding new places to put this, and `account.color` might be a bit more consistent with `account.label`, etc

**Comment by Phylu** [comment]
@bengotow Thanks a lot for your extensive explanation. This is really helpful.

I will pick this up. Probably next week.

**Comment by Phylu** [comment]
@bengotow Thanks a lot again for the pointers. The colors are updated now immediately. :)
So this should be good to go unless you have something else that I should have a look at.

**Comment by bengotow** [comment]
This looks great! Going to merge and test a bit more today before we ship an update!

**Pull request merged**
