### PR TITLE
Add information regarding app password type for FastMail

### LINKED ISSUE #2216: Fastmail: Clarify that password should be IMAP
**Describe the bug**

Fastmail supports both IMAP and JMAP.

Mail spring does not specify which protocol it uses, so when creating an app password one has to guess. Being that JMAP is led by fastmail, and the recommended  approach, one would assume that's what mailspring supports.

After generating and providing the password to mailspring, it throws an error message indicating "Check your username and password (IMAP).

It would be best to clarify what protocol mailspring will use **before** a users provides a password, since one has to chose the protocol before generating the password.

**To Reproduce**
1. Open mailspring
2. Log into mailspring
3. Select fastmail -- you're prompted for credentials
4. Head over to fastmail to generate an app password.
5. A protocol must be selected at this point. Mailspring does not indicate any, so let's assume JMAP.
6. Finish generating the app password.
7. Put the password in mailspring.
8. At this point, mailspring show an error and clarifies that I should have selected IMAP in step 5.

**Expected behavior**
Supported protocol should be shown _before_ a password is provided, since it's required to generate a password.

**Actual behaviour**
Supported protocol should be shown _after_ a password is provided, so the initial password must be deleted and another one must be generated.

**Setup: (please complete the following information):**
 - OS: ArchLinux
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 

This is more of a UX issue than anything else -- it's not a blocker, but just annoying.

### PR DESCRIPTION
**Pull request by Phylu**
Fixes #2216 and adds a German translation for FastMail while improving existing German translations for iCloud and Yahoo account creation.

### CODE REVIEW

**Comment by CodeMouse92** [comment]
Hi @Phylu! Thanks for all the hard work recently. We're setting up a Discourse community where future bug report and feature request discussions will take place, among other things. That way, our GitHub can focus on confirmed issues and excellent PRs like this. Would you be willing to sign up over there with your GitHub account?

https://community.getmailspring.com/

We also have the `mailspringofficial` Telegram channel now.

As soon as you're over there, let me know and I'll add you to the Contributors group.

**Review by WhyNotHugo — APPROVED** [review]

**Comment by bengotow** [comment]
This looks great, thanks @Phylu!

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
Passwords are still always rejected (as described in #2217).

Any hints on what should be done?

**Comment by CodeMouse92** [comment]
@WhyNotHugo Actually, yes, the conversation is continuing here. This is a high priority, but we'll need your help to diagnose it.

https://community.getmailspring.com/t/fastmail-app-passwords-are-always-rejected/65

**Pull request merged**
