### PR TITLE
Configure the select all behavior by OS instead of application template

### PR DESCRIPTION
**Pull request by Phylu**

### CODE REVIEW

**Comment by bengotow** [comment]
Hey hey! Will take a look at this one tomorrow morning, I can't quite remember how the platform keymaps and the mail-client-defaults layer on top of each other, but ideally someone with the Gmail keymaps will get both `Cmd/Ctrl-A` and also `* a` to match Gmail... 

I think that these files still more or less follow the Atom keymaps syntax (https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) so I /think/ `mod-x` actually switches from `cmd-x` to `ctrl-x` based on the platform already. 

Maybe the issue here is that cmd/ctrl-A is being overridden by the mail-client-defaults layer of settings?

**Comment by Phylu** [comment]
I think it is no Problem to configure both. I will check it out.

**Comment by Phylu** [comment]
I have confirmed that the settings work nicely along each other. So basically this PR now adds os specific settings (`Cmd/Ctrl-A`) based on the operating system while leaving the shortcuts by the application templates (e.g. GMail) in place.

**Comment by bengotow** [comment]
Thanks for double checking @Phylu I appreciate it! Going to go ahead and merge this one! 🙌

**Pull request merged**
