### PR TITLE
Upgrade electron to version 22

### PR DESCRIPTION
**Pull request by Phylu**
I have updated electron to its latest version and bumped several connected dependencies as well.

Currently tested on Linux & Mac. I will try to test this on Windows within the next days and hope that everything there works as well.

### CODE REVIEW

**Comment by Phylu** [comment]
@bengotow I am trying to remove keytar, as I don't get Mailspring to build on Windows otherwise. Keytar is deprecated. See:
* https://github.blog/2022-06-08-sunsetting-atom/
* https://github.com/atom/node-keytar

I tried to simply encrypt the credentials using the safeStorage method to encrypt the credentials nicely and then store them in the config. See: `app/src/flux/stores/credential-store.ts`

However, this does not work whatsoever. When creating a new mail account, I simply get the error message `Your Mailspring ID is missing required fields - you may need to reset Mailspring.`

If you can give me pointers of what may work, I would be grateful.

**Comment by SebTM** [comment]
Hey, regarding the mentioned CVE above this gets more time-sensitive to us (NixOS maintainers) what are your plans on moving forward here or updating to a non affected version? :)

**Comment by MikaelFangel** [comment]
@Phylu - May suggest that you update the title to something like: Upgrade electron to version 22.x.x or maybe just upgrade electron to version 22. So it's more clear that you try to upgrade to a recently patched version of Electron and not to 22.0.0.

**Comment by Phylu** [comment]
I think, I have found a solution on the keytar issue. The problem was, that I forgot about the Mailspring ID which could also be stored using keytar.

However, to write a proper migration we need at least one version that contains the new logic using the safeStorage method as well as keytar to move all the credentials to the new storage.

Therefore, I am now working on the migration step. We will need to have an intermediary Mailspring version then to prepare for this upgrade.

**Comment by Phylu** [comment]
@bengotow This should now be ready to go after we have the intermediary 1.12 version shipped. I successfully tested these changes on Linux (.deb & snap), Mac and Windows and could not find any further issues.

**Comment by Tamriel** [comment]
I unsuccessfully tried building your fork. Could you share the .deb file as a release in the fork?

**Comment by Phylu** [comment]
@Tamriel You can find a fresh temporary build here: https://nextcloud.phynformatik.de/index.php/s/GbATAMr4dofL327

**Comment by Tamriel** [comment]
I tried it on Manjaro. My mail accounts cannot connect. I get `Your Mailspring ID is missing required fields.` The doc says 'This error message appears when Mailspring was unable to save your Mailspring ID password to your system keychain or keyring.'
I installed the same dependencies as with Mailspring 1.11
Ideas?

**Comment by Phylu** [comment]
Try to follow these steps: https://community.getmailspring.com/

Logging out of your Mailspring ID temporarily should fix the issue.

**Comment by Tamriel** [comment]
I deleted the Mailspring folder `~/.config` and have installed `gnome-keyring` and `libsecret`. Nonetheless I cannot login with Mailspring ID because the credentials cannot be stored on my computer’s keyring. Mailspring 1.11 works.
The log in the console says:
```
Error: Could not call remote method 'encryptString'. Check that the method signature is correct. Underlying error: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.Underlying stack: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.
    at /usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:465:71
    at IpcMainImpl.<anonymous> (/usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:513:28)
    at IpcMainImpl.emit (node:domain:489:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:82058)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)

    at /usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:468:25
    at IpcMainImpl.<anonymous> (/usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:513:28)
    at IpcMainImpl.emit (node:domain:489:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:82058)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12) {
  cause: {
    stack: 'Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.\n' +
      '    at /usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:465:71\n' +
      '    at IpcMainImpl.<anonymous> (/usr/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)\n' +
      '    at IpcMainImpl.emit (node:events:513:28)\n' +
      '    at IpcMainImpl.emit (node:domain:489:12)\n' +
      '    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:82058)\n' +
      '    at EventEmitter.emit (node:events:513:28)\n' +
      '    at EventEmitter.emit (node:domain:489:12)',
    message: 'Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.'
  }
} { pluginIds: [] }
(node:978529) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `mailspring --trace-deprecation ...` to show where the warning was created)
```

**Comment by Phylu** [comment]
@Tamriel Can you try to start mailspring with the following parameter from the command line?

```
--password-store="gnome-libsecret"
```

Which desktop environment is Manjaro using? Maybe we need to hardcode this parameter in the Mailspring startup if there are desktop environments that are not able to be properly recognized. I happened to run in this issue on Lubunt for testing now as well. Unfortunately, this might break (newly created) compatability on KDE environments...

See also: https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

**Comment by Tamriel** [comment]
There are different flavors of Manjaro. I use the sway desktop environment. It worked with `--password-store="gnome-libsecret"`. Thanks a lot!

**Comment by Tamriel** [comment]
I installed Mailspring with an Arch User Repository package. In the package definition it is surely possible to add the flag to .desktop file file. I will add a comment the current Mailspring package, so the owner knows what to do when he updates to 1.12.

**Comment by Phylu** [comment]
I have added some more details to the corresponding help page: https://community.getmailspring.com/t/password-management-error/199/2

**Comment by bengotow** [comment]
Hey @Phylu! All the changes here look great - I shipped the 1.12.0 release which is the stepping stone to this one, and I think we should go ahead and merge this! I'll start testing off master and using the Electron 22 one as my daily email client, and we can make smaller PRs to fix anything we run in to. Thanks for all the help with this!

**Comment by bengotow** [comment]
Hey folks,

I merged this and fixed a few issues with the Travis / AppVeyor CI builds -- I've been testing the new Electron 22 version on Mac for the last day or so, and it's working great! Here are some new builds. It'd be great if you could give it a spin and let me know if there are any issues -

Ben

Windows:
- https://mailspring-builds.s3.amazonaws.com/client/89078ce5/win-x64/MailspringSetup.exe

Mac:
- Intel: https://mailspring-builds.s3.amazonaws.com/client/390a301d/osx/Mailspring.zip
- Apple Silicon: https://mailspring-builds.s3.amazonaws.com/client/390a301d/osx/Mailspring-AppleSilicon.zip


Linux:
- `snap refresh mailspring --edge` (rev 528)
- https://mailspring-builds.s3.amazonaws.com/client/89078ce5/linux/mailspring-1.13.0-0.1.x86_64.rpm
- https://mailspring-builds.s3.amazonaws.com/client/89078ce5/linux/mailspring-1.13.0-amd64.deb

**Comment by Tamriel** [comment]
I have the following issue: https://community.getmailspring.com/t/random-crash-with-1-12-on-manjaro/7336

**Comment by Phylu** [comment]
When running the .deb version of Mailspring on one of my test systems, Zorin OS based on Ubuntu 22.04, I get the following error. It seems that the latest version of better-sqlite3 is linked against glibc 2.33 wheras the older Ubuntu version(s) are shipped with glibc 2.31.

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/share/mailspring/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2096)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/usr/share/mailspring/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/usr/share/mailspring/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)
    at openDatabase (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/stores/database-store.ts:53:16)
    at DatabaseStore.open (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/stores/database-store.ts:149:22)
    at new DatabaseStore (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/stores/database-store.ts:144:12)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/stores/database-store.ts:532:16)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/stores/database-store.ts:532:36)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/models/query-subscription.ts:1:1)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/models/query-subscription.ts:330:2)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/models/query-subscription-pool.ts:2:1)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/flux/models/query-subscription-pool.ts:119:21)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/global/mailspring-observables.ts:4:1)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/global/mailspring-observables.ts:171:3)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new AppEnvConstructor (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/app-env.ts:116:5)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/secondary-window-bootstrap.ts:30:17)
    at Object.<anonymous> (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64-KEmML7/resources/app/src/secondary-window-bootstrap.ts:38:49)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at setupWindow (file:///usr/share/mailspring/resources/app.asar/static/index.js:46:3)
    at window.onload (file:///usr/share/mailspring/resources/app.asar/static/index.js:74:5) {
  code: 'ERR_DLOPEN_FAILED'
} {}
```

**Comment by Phylu** [comment]
On my Ubuntu 23.10 computer, I encounter the following issue after installing Mailspring 1.13 from the .deb file.

[Bildschirmaufzeichnung vom 2023-11-18, 16-03-30.webm](https://github.com/Foundry376/Mailspring/assets/587332/f7afb52f-9d0f-492d-b2f9-a311446c30ac)

**Comment by Phylu** [comment]
> This seems to be spellcheck related, happening when the spellchecker wants to highlight a word or part of a sentence, deleting it instead.

@bengotow: I could boil this one down to an issue in adding the decorators for spelling errors. If I uncomment the ` editor.setDecorations()` method call at these locations, there is no more text getting deleted (while no spellcheck happens anymore - of course). I saw, that the version of `slate` in use is customized in https://github.com/bengotow/slate. Maybe you can have a look at this and maybe even get back onto the main version, to be able to upgrade this dependency.

- https://github.com/Foundry376/Mailspring/blob/master/app/src/components/composer-editor/spellcheck-plugins.tsx#L163
- https://github.com/Foundry376/Mailspring/blob/master/app/src/components/composer-editor/spellcheck-plugins.tsx#L202

**Comment by bengotow** [comment]
Hey hey! Taking a look at the spellcheck issue now -- I was able to fix the GLIBC compatibility problem (at least on my Ubuntu 18 machine) by using an older linux to build the app in CI. Want to try this file and see if it works for you as well?


https://mailspring-builds.s3.amazonaws.com/client/fbb68340/linux/mailspring-1.13.0-amd64.deb

**Comment by Phylu** [comment]
> Taking a look at the spellcheck issue now

Looking forward to seeing this fixed! 

> I was able to fix the GLIBC compatibility problem (at least on my Ubuntu 18 machine) by using an older linux to build the app in CI. Want to try this file and see if it works for you as well?

@bengotow Nice. I can confirm that this version runs on both my Ubuntu 23.10 as well as my 22.04 test system (which did not run the build that was linked against the newer glibc).

**Pull request merged**
