### PR TITLE
Electron upgrade to 14.2.1

### LINKED ISSUE #2352: Upgrade to Electron 12
## Objective

It'd be very helpful if Mailspring was updated to use Electron 12 (instead of Electron 8). Upgrading to Electron 12 would make Mailspring arm64 compatible (much needed, since all future macs are going to be arm64 for a long period of time) and also unlock support for Wayland which is the standard for Linux GUIs.
## Testing Notes

* Linux
* macOS

## References

https://community.getmailspring.com/t/electron-12-migration/504/2

### PR DESCRIPTION
**Pull request by Phylu**
Closes #2352

### CODE REVIEW

**Comment by mamantoha** [comment]
Hi @Phylu . I'm testing this branch for a few days. Works pretty good for me. No issues so far.

**Comment by 3v1n0** [comment]
Anything needed in the snap?

**Comment by Phylu** [comment]
@bengotow Did you have some time for testing already? :)

**Review by bengotow — APPROVED** [review]
Went through all these changes and it looks great! I haven't been able to find any bugs in a few hours of banging on things, so I'll merge it and see if I can get a Travis CI build to pass!

**Comment by bengotow** [comment]
Ok - I had to make AppVeyor and TravisCI use Node 16 and Visual Studio 2017 on Windows, but we've got builds! 🙌 I  couldn't get `npm run lint` to succeed on Node 16 because of some super out of date node dependencies buried inside grunt-lesslint, so I just dropped them for now. The tooling in VSCode has gotten so good, I think it's pretty rare a `less` error would make it through development.

I'm going to continue testing these tomorrow and ship them after lunhc if everything looks good. At this point I think it'd be better to release and then quickly fix anything that is broken since I've been sitting on this for so long. 🤦‍♂️ 

Thank you for spearheading this + tracking down and fixing the bugs @Phylu!  I made a Mailspring-Maintainers group and added you so that you have push access to the entire repository and can merge PRs that look good.   I think that will also let you trigger builds on Travis (to test things like this more easily) by logging in via Github at https://app.travis-ci.com/github/Foundry376/Mailspring.

Beta builds:

MacOS:
https://mailspring-builds.s3.amazonaws.com/client/5ff67fdd/osx/Mailspring.zip

Windows:
https://mailspring-builds.s3.amazonaws.com/client/1201bded/win-ia32/MailspringSetup.exe

Linux: 
https://mailspring-builds.s3.amazonaws.com/client/5ff67fdd/linux/mailspring-1.9.3-amd64.deb
https://mailspring-builds.s3.amazonaws.com/client/5ff67fdd/linux/mailspring-1.9.3-0.1.x86_64.rpm

**Comment by aryan9600** [comment]
The macOS build still seems to be an x86 application for some reason?
image

**Comment by Phylu** [comment]
> The macOS build still seems to be an x86 application for some reason.

The Travis build currently only creates an amd64 package. It is not compiled for arm64 yet.

**Comment by bengotow** [comment]
Hey folks! Yep still an intel build for now. We could make it a universal binary but it would double the size to 600MB. I think we need to update the download page to offer both versions and the auto-updater needs to get the correct architecture for updates. Will see if I can update it this weekend!

**Comment by rsteinberg** [comment]
Hey @bengotow! Not to be a pain but would you mind giving us an update?
Please do take your time but I ended up here when researching the status of macOS ARM support and was wondering.

**Pull request merged**
