### PR TITLE
Add setting to disable email content max width

### LINKED ISSUE #228: [Feature Request] Allow read pane to be infinitely wide and use all space
What operating system are you using? Windows 10

What version of Mailspring are you using? 1.06

**Bug?**

Cannot disable the contact side bar and unable to make the read pane take the full available space between the list of emails all the way to the right of the display.

### PR DESCRIPTION
**Pull request by mattlyons0**
Closes #228 

The default setting is still to have max width enabled, but now there is the option to disable it.

Before: before
After: after

### CODE REVIEW

**Comment by thuelinIMS** [comment]
Is there a way to enable this setting in the current release branch?

**Comment by mattlyons0** [comment]
Its been done for more than a year. Up to the maintainers if they want to merge it or not (I'm getting the feeling they don't). The CI tests didn't exist when I made the PR and there are merge conflicts because it has been more than a year.

**Comment by bengotow** [comment]
Hey folks! Ok, so we've had a lot of requests for this over the last year (recently #1504 #1398), gonna resolve these conflicts and get this merged in

**Comment by bengotow** [comment]
Hey @mattlyons0 — thanks again for submitting this,  sorry it took a ridiculously long time for it to get merged. The whole app moved to TypeScript so I ended up re-applying your changes and merging this manually. I was originally planning on making this new option to restrict the width enabled by default, but after using this for a day it feels much better letting everything go the full width by default.

Also I decided that for now, it wasn't worth observing the config value because the pref has to be read in a few places. Hopefully that's not too bad for now.

**Pull request closed without merging**
