### PR TITLE
Added "Show original" in Message controls Actions Menu

### PR DESCRIPTION
**Pull request by debba**
I love this product and would like to contribute a little bit actively both in terms of internal functions and developing external plugins.

One thing I find really difficult is showing the original content of the email.
On my Ubuntu is very tricky enabling the secret context menu using the right button.
I thought that integrating it directly into the dropdown would not be bad, personally I find it very useful.

Maybe could be good prepend an icon too, as in other dropdown menu items.

Schermata da 2020-04-24 09-52-55

### CODE REVIEW

**Comment by bengotow** [comment]
Hey thanks for submitting this! I agree this needs to be included more prominently... the "secret menu" was really just debug stuff until the "Show Original" feature was added there, but it's a useful option everyone should know exists.

I think Mailspring's main menu (and keyboard shortcuts, etc.) have been a bit lacking in message-related options like this because there's no concept of "selection" in the conversation / messages panel. A lot of other apps show a "focus ring" or highlight of some sort around the currently selected message, and items in the app's menu operate on that selection. Long term I'd love to fix that.

This seems like a great approach to take in the short term though. Gmail's message menu has a similar placement and is packed with all sorts of good stuff. Hopefully this can be a starting point for us to add more options like this:

image

**Comment by bengotow** [comment]
The code for this looks great—I'm going to go ahead and merge it, and I'll see if I can fix the Menu component so that it indents the menu items without images to match the ones that have them.

**Comment by ashb** [comment]
@bengotow Are you aware that this was already there, just there is a hidden (i think, accidentally) menu for this

image

(Click on the red arrow to get that menu shown to pop up)

And the reason for that is that the component on that has a css rule of `object-position: 10000px center;` Remove that and it looks like this:

image

(Yes, spacing is off)

**Comment by CodeMouse92** [comment]
Hi @debba and @ashb, I just wanted to let you know that we've launched the [Mailspring Community](https://community.getmailspring.com). It will be home to all future bug reports, feature suggestions, and plenty of development discussion. We'd love for you to join!

When you do, you can request to be a member of the Contributors group here: https://community.getmailspring.com/g/contributors

Looking forward to seeing you on there!

-Jason C. McDonald
Volunteer Community Manager
Mailspring

**Pull request merged**
