### PR TITLE
Making composer recipient name warnings optional

### PR DESCRIPTION
**Pull request by arhanjain**
Hey, this is my first stab at open source contributions. I'm working on [this feature suggestion](https://community.getmailspring.com/t/make-composer-recipient-name-warnings-optional-add-dont-warn-me-again-option/630). So far I've split the `DraftSession::validateDraftForSending` by making a separate `validateDraftRecipients` as described by @bengotow. I will start working on the portion of adding a button to ignore warnings for that email, but wanted to check whether my approach for the first part is acceptable or requires tweaking.

### CODE REVIEW

**Comment by Phylu** [comment]
Hey @arhanjain 

Thanks a lot for taking this up! As I am traveling right now, I could only take a short glance via mobile, but I could not spot and big issues with the code. So, I would say, feel free to go on with it! I will definitely have another look once I am back (unless Ben did this already in the meantime).

Cheers Phylu.

**Comment by arhanjain** [comment]
I believe the changes specified in the feature suggestion have been implemented with these commits. Let me know if there's any issues or improvements I can make, but no rush. Enjoy your travels Phylu :)

**Comment by Phylu** [comment]
Just had another quick view. I think, there should also be an option (in the preferences) to reset the emails that don't get the warning anymore.

If I remember correctly there is a button with similar functionality for resetting the spellchecking that you might want to have a look at.

**Review by bengotow — APPROVED** [review]
Thanks for making the updates to this, I think it looks great! We're doing another Mailspring release soon and I'll make sure this gets shipped. I think the only comment I have is that the new button title ("Send & Ignore Warnings For This Email") might be awkwardly long on a Mac, but I'll give it a spin and see. 

Thanks!

**Pull request merged**
