### PR TITLE
Rename mailspring.desktop to Mailspring.desktop

### PR DESCRIPTION
**Pull request by Phylu**

### CODE REVIEW

**Comment by bengotow** [comment]
Hey @Phylu! This looks good to me, but do you know if caps / lowercase are standard for these? I mostly just want to make sure it aligns with people's expectations - I think I originally set it up this way because on Ubuntu, the `/usr/share/applications` folder seemed to have lowercase items but it may be that they're not seen by the user?

image

**Comment by CodeMouse92** [comment]
@bengotow If we want to talk about standardization, the reverse domain style is more "standard". That said, anything goes for this, and as it fixes a bug, I think it's worth landing until we put in the work to change and test the entire thing.

**Comment by Phylu** [comment]
I think the other alternative would be to rename "Mailspring" to "mailspring" as the application name. That seemed more complicated as the name is substituted from a variable and I was not sure about the side effects. I can try this as an alternative though.

**Comment by Pajn** [comment]
Ubuntu/debian packagers use either lowercase or namespace with application name uppercase (ex. `org.gnome.Calculator.desktop` so there isn't that much consistency to start with and other distros might do it differently and for third party applications it's very mixed. I think flatpak standardises the namespace/reverese domain style so if consistency is desired I would argue `com.getmailspring.Mailspring.desktop` is the correct name but as mailspring does not support flatpaks yet, go with the most simple variant.

**Comment by bengotow** [comment]
Hey folks—sounds good! Thanks for the feedback, I think we can switch to `Mailspring.desktop` for now to fix the bug, and then see about switching to the namespace approach if we ship a flatpak and are making other changes here. 👍

**Comment by shawnk0723** [comment]
This doesn't work in KDE. Not sure if it depends on the distro. FYI, I'm using Arch.

**Comment by shawnk0723** [comment]
> Hey folks—sounds good! Thanks for the feedback, I think we can switch to `Mailspring.desktop` for now to fix the bug, and then see about switching to the namespace approach if we ship a flatpak and are making other changes here. +1


This doesn't work in KDE. Not sure if it depends on the distro. FYI, I'm using Arch.

**Pull request merged**
