### PR TITLE
Added the leading 'www' to the social links in the sidebar, now curso…

### PR DESCRIPTION
**Pull request by alemagio**
…r pointer is shown wheh hovering social links in the sidebar

### CODE REVIEW

**Comment by coliff** [comment]
would this add `www.` to ALL social links? We wouldn't want them added to Twitter.com as they don't use www... it's just Facebook and LinkedIn that should have `www.`

**Comment by alemagio** [comment]
Hi did what I think is the best fix for the current issue, but, for what I saw, the same issue is in other parts of the code (company profile).
Maybe we could think of a more deep fix to handle this problem in general.

**Comment by bengotow** [comment]
Hey thanks for contributing this! It looks like this breaks the tiny little "facebook" and "twitter" icons because the img src is `mailspring://participant-profile/assets/${service}-sidebar-icon@2x.png`. 

It's nice and succinct to use the `service` prop, but could you add a new `hostname` prop to the `SocialProfileLink` that gets passed in alongside the handle and service? I think that'd allow us to customize it a bit more:

```
            <SocialProfileLink service="facebook" hostname="www.facebook.com" handle={facebook && facebook.handle} />
```

(Eventually I'm sure we'll want one that isn't a .com, so it'd be nice to have this in place for that too!)

**Comment by alemagio** [comment]
Hey, i just updated the code following your suggestions.
As i mentioned in the previous comment i noticed that the same issue affected the company profile too.
I fixed that too, hope is fine.

**Comment by bengotow** [comment]
Hey @alemagio - I'm sorry for the delay getting this reviewed and merged, this looks great! I appreciate you fixing the company profiles too, I think this definitely needed to be added there too.

Thanks! The CI failure is unrelated unfortunately, I need to take a look at that separately!

**Pull request merged**
