### PR TITLE
Red icon for new mail and blue icon for unread mail

### PR DESCRIPTION
**Pull request by marivaldojr**
This PR adds unread icon for system tray with following logic:

- Red icon means there are new mails since you last foregrounded the app
- Blue icon means there are unread mails

### CODE REVIEW

**Comment by bengotow** [comment]
I think this looks good! I could see this being potentially annoying if you're not an inbox zero user (if you always have unread mail, the icon will always be flipping between blue and red in the menu bar as you foreground / background the app), but let's give it a spin and see - I could see making this a configuration option one day if it's contentious. 

Thank you for the cotnribution!

**Comment by ipkpjersi** [comment]
@bengotow 
I'm a bit surprised a fairly large change like this isn't a configuration option. To me, a red icon means it's having connection issues. It's distracting and looks out of place. 

It's honestly bothering me enough to the point where I'm wanting to start looking for other mail apps until this is made into a configuration option, unfortunately.

**Comment by aia832003** [comment]
Add my vote for this needs to be an opt-in option. I also like that this is a tray indication for lost connection to an account versus new mail. Wasn't the blue icon color already doing this? Even if I had it in focus recently but received a new email it turned blue?

**Comment by snakeeyes021** [comment]
> I think this looks good! I could see this being potentially annoying if you're not an inbox zero user (if you always have unread mail, the icon will always be flipping between blue and red in the menu bar as you foreground / background the app)

I'm a little confused by this. How is it supposed to work? I have a single unread email that I don't want to mark as read yet. Icon is blue. I go do other things. Icon turns red. I assume this means new mail has come in. Nope. Same single message as before, but by focusing on the app window to check, icon turns back to blue. Go do other things. Icon turns red again. Still no new mail. Rinse and repeat. This can't be intended behavior, can it? If so, this is indeed, as suspected, very annoying (I don't need my email app going literal code red to tell me about a message I've already noted; and fwiw I agree that red generally indicates a problem). If not, needs a little more time in the oven. Either way, it absolutely needs an option to disable.

**Pull request merged**
