### PR TITLE
Update the icon for Windows

### PR DESCRIPTION
**Pull request by erryox**
Hi,

Please update the icon for Windows client. Square icon with the hard edges out of the general style. I just replaced the icon with a standard one from other systems. 
screen

### CODE REVIEW

**Comment by bengotow** [comment]
Hey! Thanks for contributing this—I can't remember why we started publishing a separate icon for Windows. I think it was so that the app looked good in the Windows 10 "start menu" thing (Both in a large square and in the list)

image

Do you know if there's any way to retain the square appearance in there while using a round icon elsewhere? (Or is that even something we should consider doing?) It'd certainly be easier for us to just have one style...

**Comment by erryox** [comment]
Hi!
Hmm, I get your point. 
изображение
But for some reason square icons are displayed in another square, that doesn't look perfect anyway :)
IMHO round icons look even better, Telegram, Chrome, etc.

I would love to help you, but unfortunately I don’t know how. Firefox, Chrome and Skype somehow do it (You can see this on the screenshot). 
Perhaps you should see how it's done in UWP apps: https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos

Btw, this is how it will look with the round icon:
изображение

**Comment by erryox** [comment]
Hey!

I found out how to make a round icon for the app and square tile for the start menu. You just need to place `mailspring.VisualElementsManifest.xml` near `mailspring.exe`. Which should contain something like that:
изображение
[https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-visualelements](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-visualelements)

Also, you can see how Firefox do that in this folder `C:\Program Files\Mozilla Firefox`.

**Comment by bengotow** [comment]
Oh wow that's a great find! Thanks for digging in to this - I've been wondering how other apps did that for so long! I'll merge this and see if I can add a `mailspring.VisualElementsManifest.xml` file.

**Pull request merged**
