### PR TITLE
Added signature icons for Medium, GitHub and YouTube

### PR DESCRIPTION
**Pull request by sudeephazra**
Added signature icons for Medium, GitHub and YouTube

### CODE REVIEW

**Comment by sudeephazra** [comment]
Enhancement details outlined at https://community.getmailspring.com/t/additional-links-in-signature/7874

**Comment by sudeephazra** [comment]
Please deploy the icons at the following locations
- https://www.getmailspring.com/signature-assets/youtube.gif
- https://www.getmailspring.com/signature-assets/github.gif
- https://www.getmailspring.com/signature-assets/medium.gif

**Comment by sudeephazra** [comment]
@bengotow Tagging for your attention on this 😃

**Comment by bengotow** [comment]
Sorry for the [very long] delay here -- I am deploying those resources now and we'll get this shipped!

**Review by bengotow — APPROVED** [review]

**Comment by sudeephazra** [comment]
Thanks @bengotow 😊

**Pull request merged**
