### PR TITLE
Changes in pl

### PR DESCRIPTION
**Pull request by vertoo**
Some polish updates.

### CODE REVIEW

**Comment by odie2** [comment]
Hi @bengotow, of course I can compare these strings too, but sadly I can not get to diff between current version with merged PR, the [only diff I found](https://github.com/Foundry376/Mailspring/pull/1152/files) compares with old file version, maybe it needs time to be refreshed?

**Comment by vertoo** [comment]
Hi @bengotow @odie2,
I [compare](https://github.com/Foundry376/Mailspring/compare/master...vertoo:master) master to my changes and I think my changes are better.

**Comment by odie2** [comment]
@vertoo 

Do you see comparision with current master or old? I see sadly with old, first version of non-reviewed localization: 

opera_2018-10-26_12-32-07

Actually current file looks like this, so I can not truly get compare master to your changes, seems like GitHub compares master from 3 days back and I am not able to see how compare with current master:

opera_2018-10-26_12-34-34

**Comment by vertoo** [comment]
@odie2 you have right, this is compared to old master. Just downloaded latest master and compare in Meld.
In conflict lines I think my translations are better. What do you think?
Another changes are better on current master.
```
lines 505, 506
master:
"Reading Pane Off": "Panel czytania wyłączony",
"Reading Pane On": "Panel czytania włączony",

my:
"Reading Pane Off": "Bez podglądu wiadomości",
"Reading Pane On": "Panel podglądu wiadomości",
```

```
line 585
master:
"Select All Unread": "Zaznacz wszystko nieprzeczytane",

my:
"Select All Unread": "Zaznacz wszystkie nieprzeczytane",
```

**Comment by odie2** [comment]
@vertoo 

Yes, I think your lines 505, 506 and line 585 are better :)

**Comment by vertoo** [comment]
@bengotow you are free to copy&paste my lines 505, 506, 585 to current master. Or I can create new commit and pull request. But copy&paste will be much faster :)

**Comment by odie2** [comment]
Added in #1175, thanks.

**Comment by bengotow** [comment]
Beautiful - thank you guys! Really appreciate it :-) I'm preparing a patch release so these will go out soon! If everything has been addressed from the original PR want to go ahead and close this?

**Pull request closed without merging**
