### PR TITLE
Handle nautilus-sendto links

### LINKED ISSUE #2289: Attach files via sendto dialogue
## Objective
On Linux systems do a right click to a file in the desktop environment and chose "Send To" in order to attach a file to a Mailspring e-mail. This currently only opens an empty e-mail without the attachment. [1]

## Testing Notes
Behaviour is probably different for different desktop environments. Development is done on gnome and will match the nautilus-sendto behaviour [2].
Therefore this should be checked on other desktop environments (e.g. KDE) as well.

## References

[1] https://community.getmailspring.com/t/right-click-send-via-mail-opens-new-email-dialog-but-doesnt-attach-file-kde-neon-dolphin-file-explorer/644/3
[2] https://gitlab.gnome.org/Archive/nautilus-sendto/-/blob/master/src/nautilus-sendto.c

### PR DESCRIPTION
**Pull request by Phylu**
Closes #2289.

Unfortunately only tested on Gnome and not within another desktop environment. I am happy to do further changes if necessary.

### CODE REVIEW

**Comment by CodeMouse92** [comment]
I'll make a note to test this out in XFCE later.

**Review by CodeMouse92 — CHANGES_REQUESTED** [review]
On XFCE (Nautilus), I get the following error message when I try to use `Send To... > Mail Recipient`.

> ?attach=file:///home/jason/usenet.txt& could not be found, or has invalid file permissions.

I suspect you need to handle the possibility of multiple arguments separated by the `&`, especially the possibility of a *trailing* ampersand.

Screenshot_2021-02-25_11-50-41

**Comment by Phylu** [comment]
@CodeMouse92 Thanks for testing. It seems that the `mailto:` is missing that nautilus-sendto automatically adds on my Ubuntu/Gnome system.

* Can you please add a `console.log(args);` to the file `app/src/browser/main.js` in line 127 (in the `parseCommandLine` method) and provide the output?
* You should get the very same error message if you try the sendto menu entry running from the current master branch or the latest release. Is this correct?
* Do you have the package "nautilus-sendto" installed that is handling the menu entry, or is this a different program?

**Comment by CodeMouse92** [comment]
> Do you have the package "nautilus-sendto" installed that is handling the menu entry, or is this a different program?

As I said, this is Thunar on XFCE, not Nautilus. There are several different major file browsers on Linux, and *none* of them work with Mailspring. One fix should cover 'em all, as they all follow basically the same convention. In this case, [thunar-sendto-email](https://github.com/xfce-mirror/thunar/tree/eb273d02f031273e4a50ea212f942e1892ec7552/plugins/thunar-sendto-email) is being used.

> You should get the very same error message if you try the sendto menu entry running from the current master branch or the latest release. Is this correct?

Ah, good thought. Yes, same error with 1.8.0.

> Can you please add a console.log(args); to the file app/src/browser/main.js in line 127 (in the parseCommandLine method) and provide the output?

I'm probably overlooking something, but I can't find where that logs to. It's neither in the terminal or Developer Tools. However, I do have this from when Mailspring was automatically invoked on the command-line:

> electron ./app --enable-logging --dev "%U" "?attach=file:///home/jason/python.peril&"

So, no, it doesn't have `mailto:`. However, I suspect you *could* work around that?

P.S. That took some doing. I had to change the Preferred Application startup to this: `xfce4-terminal -e "npm start --prefix ~/repos/Mailspring -- %U "%s""`

**Comment by Phylu** [comment]
@CodeMouse92  Thanks a lot for the additional hints. I was a bit confused as you have been talking about
> XFCE (Nautilus)

instead of thunar in your original test report.

I have adjusted this by adding the `mailto:` for thunar based links so that they can be handled easily using the `URL` based solution that works nicely for nautilus-sendto.



@Furqan136 would you be able to provide a test case for KDE as you originally reported this here: https://github.com/Foundry376/Mailspring/issues/1319

**Comment by CodeMouse92** [comment]
> I was a bit confused as you have been talking about

>> XFCE (Nautilus)

> instead of thunar in your original test report.

Oops, my mistake! I apologize.

I'll try to test this out later today and confirm the fix.

**Comment by Phylu** [comment]
@CodeMouse92 Just checking in, so this doesn't get forgotten. Did you manage to test the updated changes yet?

**Comment by CodeMouse92** [comment]
I was going to do that next, as a matter of fact. Stand by.

**Comment by CodeMouse92** [comment]
Hmm. Still not working. Same error as before.

I do notice the terminal output does indicate this is the full mailto being handled:

```
mailto:?attach=file:///home/jason/python.peril&
```

**Comment by CodeMouse92** [comment]
Ignore my (now deleted) comment from a moment ago. It *does* work now! (Minor error on my end.)

It's a happy land from XFCE/Thunar. Woot woot!

**Review by CodeMouse92 — APPROVED** [review]

**Comment by bengotow** [comment]
Ahh man, I really appreciate everyone jumping in to test this on different platforms! If it were just me I'd have never gotten this quite right. Also thanks for commenting this code, I'm sure we'll come back to this one day and need the context! 🙌

**Pull request merged**
