### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by EdR13**
Some sentences that are not correct in Spanish have been changed.

Added opening punctuation in some sentences.

Added or changed letters in words to match the correct form of the word in Spanish.

### CODE REVIEW

**Review by javiermartingonzalez — APPROVED** [review]

**Comment by bengotow** [comment]
Hi @EdR13 thanks for submitting this! These changes look good, but we merged https://github.com/Foundry376/Mailspring/pull/2393 first, and it looks like there were a few changes that conflicted with yours. Could you try rebasing your edits on top of @javiermartingonzalez's changes?

**Comment by javiermartingonzalez** [comment]
I made a merge with both changes but I don't have permissions to upload to @EdR13 PR to be reviewed.

[es.zip](https://github.com/Foundry376/Mailspring/files/8501624/es.zip)

**Comment by bengotow** [comment]
Looks like @EdR13 rebased this on master so we should be set! (Sorry for pushing two commits to this, I didn't realize that I needed to choose "Squash and Merge" because "Rebase and Merge" was the default and it was disabled)

**Comment by nolddor** [comment]
Causes https://community.getmailspring.com/t/mailspring-does-not-open-anymore/5272 ??

```
nolddor@computer:~$ mailspring
App load time: 191ms
[2810:0810/082221.571054:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
SyntaxError: /usr/share/mailspring/resources/app.asar/lang/es.json: Unexpected token 
 in JSON at position 11870
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1183:22)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.initializeLocalization (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/intl.ts:205:21)
    at Application.start (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/browser/application.ts:56:5)
    at App.<anonymous> (/usr/share/mailspring/resources/app.asar/src/browser/main.js:370:24)
    at App.emit (node:events:390:28)
    at App.emit (node:domain:475:12) Promise {
  <rejected> SyntaxError: /usr/share/mailspring/resources/app.asar/lang/es.json: Unexpected token 
   in JSON at position 11870
      at parse (<anonymous>)
      at Object.Module._extensions..json (node:internal/modules/cjs/loader:1183:22)
      at Module.load (node:internal/modules/cjs/loader:988:32)
      at Module._load (node:internal/modules/cjs/loader:829:12)
      at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
      at Module.require (node:internal/modules/cjs/loader:1012:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.initializeLocalization (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/intl.ts:205:21)
      at Application.start (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/browser/application.ts:56:5)
      at App.<anonymous> (/usr/share/mailspring/resources/app.asar/src/browser/main.js:370:24)
      at App.emit (node:events:390:28)
      at App.emit (node:domain:475:12)
}
(node:2773) UnhandledPromiseRejectionWarning: SyntaxError: /usr/share/mailspring/resources/app.asar/lang/es.json: Unexpected token 
 in JSON at position 11870
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1183:22)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.initializeLocalization (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/intl.ts:205:21)
    at Application.start (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/browser/application.ts:56:5)
    at App.<anonymous> (/usr/share/mailspring/resources/app.asar/src/browser/main.js:370:24)
    at App.emit (node:events:390:28)
    at App.emit (node:domain:475:12)
(Use `mailspring --trace-warnings ...` to show where the warning was created)
(node:2773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2773) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Raven: 429 - undefined

```

**Pull request merged**
