### PR TITLE
Fixed unread tray icon always showing when windows is blurred (#1017)

### PR DESCRIPTION
**Pull request by Harvzor**
https://github.com/Foundry376/Mailspring/pull/1206

> @Harvzor could you please submit this PR again and sign the CLA?

### CODE REVIEW

**Comment by Harvzor** [comment]
I seemed to have signed it now. Let me know later if it says it's still not signed.

Thanks!

**Comment by mkhazov** [comment]
@Harvzor it seems your commit is authored by email not associated with your github account.

**Comment by bengotow** [comment]
Rebased this and pushed it up as de079894

**Comment by Harvzor** [comment]
Sweet, I can give Mailspring another when this is released. 😎

**Pull request closed without merging**
