### PR TITLE
Fix login to Office 365 Accounts

### PR DESCRIPTION
**Pull request by Phylu**
This resolves a bug, where it is no longer possible to authenticate to Office 365 e-mail accounts as described here: https://community.getmailspring.com/t/login-to-office-no-longer-working/4071

### CODE REVIEW

**Review by ja-wa — APPROVED** [review]

**Comment by petarhtec** [comment]
Hi! When can this fix be merged, and a new version released?

**Review by bengotow — APPROVED** [review]

**Comment by bengotow** [comment]
This looks good to me folks! Thanks for submitting the fix @Phylu, I'll take a look through the other PRs and maybe we do a release later today? Seems like this is a good one to get out!

**Comment by petarhtec** [comment]
Hi, when can we expect the new release that will have this fix?
Thanks

**Comment by Phylu** [comment]
At the moment the updated windows version is not building yet on the build server. This needs to get resolved before the release. Unfortunately, there is no date I can give you, but it will be as soon as possible.

**Comment by petarhtec** [comment]
Thanks for the response!
Is it not possible to release working platforms only ex linux/macos, and release windows later? Alternatively, could I get the RC build for MacOS?

**Comment by bengotow** [comment]
Hey folks! I was able to get the builds working last night and released 1.10.3 just now.

@Phylu the only caveat was that I downgraded from Electron 18 to Electron 17.4 - in my Linux VM, Electron 18 was rendering text horribly mangled. Some sort of GPU issue I think - adding the `--disable-gpu` flag to the app fixed it, but I wasn't sure how many users would need to do that. It impacts the default sample Electron app too, so I'm hoping it's a bug that gets fixed in the next couple weeks and we can move to Electron 18 then.

**Comment by Phylu** [comment]
@bengotow Awesome. I just saw it. :)

Very strange Electron bug. Do you have an issue link so I can monitor it?

**Comment by kg-currenxie** [comment]
I can log in via the web, and I get 
```
You're all set!
Go back to Mailspring to finish linking your account and configuring the app.
```

But mailspring later says `Authentication Error - Check your username and password. (SMTP)` 

Any ideas?

**Pull request merged**
