### PR TITLE
Collect Characters Typed while Showing move-picker-popover

### LINKED ISSUE #242: Capture Keyboard Input in folder/label dropdowns faster
##### Are there any related issues?
Couldn’t find any.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.6

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

**Feature Request?**

If I use the keyboard shortcut to move a message (<kbd>l</kbd> in the Gmail keymap), I type the name of the folder directly aftewards and hit Enter (after confirming with a quick glance that the correct folder is selected). This is the workflow I’m used to from other clients.

Mailspring, on the other hand, has a little delay until the folder selector is shown, which is no problem on its own. However, Mailspring only captures the keyboard input after the selector is shown. Thus, my first few keystrokes are often lost because I forget to wait for the selector.

I suggest to find a way to capture the keyboard input directly (like in an input box off-screen), so that no keystrokes are lost until the selector is shown.

In the cast below, i was hitting <kbd>l</kbd> and typed “Newsle” to put the mail in my Newsletter folder. However, Mailspring only captured “wesle” and hence did not find the folder.

folder type

##### Does this feature exist in another mail client or tool you use?
Thunderbird (with quick-folder-move add-on)

### PR DESCRIPTION
**Pull request by jGleitz**
Fixes #242

The characters typed between triggering the popover and the popover’s input field getting the focus were lost and sometimes triggered unwanted actions.

This implementation listens to all keypresses between the rendering of the component and the search input field getting the focus.

~Note that it’s not possible to fix the issue by giving the input the focus sooner. Because focusing the input can be done only *after* it was added to the DOM. But the focus will be given to the input asynchronously, which means that keypresses that came earlier will be handled before the input gets the focus.~

### CODE REVIEW

**Comment by jGleitz** [comment]
@bengotow the CLA states that I am making the contract with SAP SE–this is a mistake, right?

**Comment by jGleitz** [comment]
Note that the implementation relies on the keypress event handler to be called before Mousetrap’s handlers are, to suppress the usual commands. This will always work because the handlers are registered for the capture phase.

If that seems too hacky, another solution would be to suspend Mousetraps somehow.

**Comment by bengotow** [comment]
Whoa what's the deal with that CLA... it almost looks like it reverted to their template somehow. I'm gonna go check on CLA bot...

**Comment by bengotow** [comment]
Ok—CLA bot should be fixed now. Thanks for catching that—surprised nobody had noticed yet.

I ran a performance profile opening the move picker via a hotkey and then immediately typing a folder name, and it takes a crazy long time to gain focus. If we can, we should try to give the focus to the input faster — maybe even immediately — so we don't need the capture approach. (It does look cool, but it'd be nice if we could fix this for all popovers.)

image

Edit: Actually... looking at that screenshot, it looks like both the LabelPicker and the FolderPicker are responding to the same key event, and the label picker calls `focusElementWithTabIndex` after the folder picker. I think it's stealing the focus, and the browser doesn't correct the issue until the end of the CSS animation that opens the panel.

This might be related to https://github.com/Foundry376/Mailspring/issues/169—if we split the keyboard shortcuts apart and prevent them both from responding, it might capture input immediately!

**Comment by jGleitz** [comment]
> Actually... looking at that screenshot, it looks like both the LabelPicker and the FolderPicker are responding to the same key event, and the label picker calls focusElementWithTabIndex after the folder picker.

That might be the case for Google accounts, but that doesn’t happen for IMAP accounts:

performance

So while fixing that is desirable, it wouldn’t fix #242.

**Comment by jGleitz** [comment]
> I ran a performance profile opening the move picker via a hotkey and then immediately typing a folder name, and it takes a crazy long time to gain focus. If we can, we should try to give the focus to the input faster — maybe even immediately — so we don't need the capture approach. 

Giving the input the focus faster was my first approach, but I didn’t succeed. No matter what I did, the focus was always given to the input ~300ms after the render method was called.

Here is another performance screenshot. In this version, I explicitly requested focus in `componentDidMount`. Nevertheless, the input only gains focus (focus timeStamp) after a timer fires, which calls `focusElementWithTabIndex` (all the way to the right in the screenshot).

Unforntunately, I have no idea why calling `focus()` has no effect.

focus performance

**Comment by jGleitz** [comment]
@bengotow  Are you still interested in this PR (fixing the bug with the workaround of manually collecting the keys that were typed until the search input got focus)? I’ll update it if you want it and close it if you don’t.

**Comment by victortrac** [comment]
This is a big problem for me. I often hit 'l' and start typing (muscle memory in gmail) and inadvertently trigger other shortcuts like archive before the the focus event happens. I'd love to see this problem fixed.

**Pull request closed without merging**
